cities:
- name: New York
  state: New York
  noaa_station_id: GHCND:USW00094728
  eia_ba_code: NYIS
  latitude: 40.7128
  longitude: -74.006
- name: Chicago
  state: Illinois
  noaa_station_id: GHCND:USW00094846
  eia_ba_code: PJM
  latitude: 41.8781
  longitude: -87.6298
- name: Houston
  state: Texas
  noaa_station_id: GHCND:USW00012960
  eia_ba_code: ERCO
  latitude: 29.7604
  longitude: -95.3698
- name: Phoenix
  state: Arizona
  noaa_station_id: GHCND:USW00023183
  eia_ba_code: AZPS
  latitude: 33.4484
  longitude: -112.074
- name: Seattle
  state: Washington
  noaa_station_id: GHCND:USW00024233
  eia_ba_code: SCL
  latitude: 47.6062
  longitude: -122.3321
api_endpoints:
  noaa_base_url: https://www.ncei.noaa.gov/cdo-web/api/v2/
  eia_base_url: https://api.eia.gov/v2/electricity/rto/daily-region-data/data/
data_paths:
  raw_data_dir: data/raw
  processed_data_dir: data/processed
  output_data_dir: data/output
